### ISSUE TITLE
Desperately need Hierarchical Modelling framework in Godot4

### ISSUE THREAD

**Issue by GeorgeS2019** [Lecrapouille/Statecharts#19]

**Comment by Lecrapouille** [comment]
1/ What is your definition of "Hierarchical system modeling" ?
- block diagrams instead of writting Godot code like done in Simulink ?
- state machine, you can use this one: https://github.com/MrBSmith/StateGraph
- Petri nets are more made for simulating concurrent systems.
- GRAFCET is the ancestor of state machine mainly used in industrial automata.

2/ Why Godot needs that ?
- Do you mean integrating inside the Godot editor ?
- Or do you mean make tools made with Godot ?

**Comment by GeorgeS2019** [comment]
> Hierarchical system modeling"

More for **visualization** than the concept

More complex petri net is best done using Hierarchical visualization to reduce challenges in automatic layout.  A group of nodes are encapsulated within one node and yet the necessary inputs and outputs leading to this group of nodes are exposed by this group node.

> 2/ Why Godot needs that ?
> 
> Do you mean integrating inside the Godot editor ?
> Or do you mean make tools made with Godot ?

Godot is not just used for game, but non-game simulation 

PetriNET is ONE of many ways to provide such simulation

**Comment by Lecrapouille** [comment]
Ah ok you mean "sub-node" yes this tool does not manage hierarchical state machine because of poor C++ design I used. My Petri net editor does not manage sub-nets/macro-nets neither.

**Comment by GeorgeS2019** [comment]
Very fee are doing it. The Japanese tried. They are doing large scale petri Ney.

Need a more flexible and mature framework to get there

**Comment by Lecrapouille** [comment]
Have you some real world example that needs Petri with so many deep sub nodes ?

**Comment by GeorgeS2019** [comment]
Biological biochemical networks attempting to explain e.g. diabetes or cancer.

Again, time petrinet is just one of many.

The key is visualization that is agnostic to the modelling backend

**Comment by Lecrapouille** [comment]
They are many graph editor made in dear im gui and godot https://www.youtube.com/watch?v=ZD9X3uvyWmg this tool only parse plantuml state machine scripts.

**Comment by GeorgeS2019** [comment]
Soon we have another way to consume plantUML :-)
